name: "Update Yandex.Browser hashes"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "38 12 * * *"
  workflow_dispatch:
  
jobs:

  update-hashes:
    name: Update Yandex.Browser hashes
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        
    - uses: cachix/install-nix-action@v15
      with:
        extra-nix-config: |
          min-free = 3000000000
          max-free = 6000000000
          
    - run: nix run .#update
