name: "Update Yandex.Browser hashes"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "38 12 * * *"
  workflow_dispatch:
  
jobs:

  update-hashes:
    name: Update Yandex.Browser hashes
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          min-free = 3000000000
          max-free = 6000000000
          
    - run: |
        set -x
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        nix run .#update
        STATUS=$(git status -s)
        if [ -n "$STATUS" ]; then
            git add json/yandex-browser-stable.json json/yandex-browser-beta.json
            git commit -m "$(date) hashes"
            git push
        fi
